### ISSUE TITLE
Example: single_cell_model.py fails and does not run

### ISSUE THREAD

**Issue by mgiugliano** [arbor-sim/arbor#1982]
After pip-installing Arbor, executing the example `single_cell_model.py` fails, returning the error:
```python3
    .paint('"soma"', arbor.density("hh"))
AttributeError: 'NoneType' object has no attribute 'paint'
```

Note: both `.paint` and `.place` fail (unless commented out)

**Context**
I get the same error both on my macOs laptop (Arbor 0.7, OS Monterey 12.6, Python 3.10.6) and using [this](https://colab.research.google.com/drive/1XMyir2ChLRtkx47iuwb0-pTZdH8wFiTv?usp=sharing) Google Colab.

**Comment by thorstenhater** [comment]
Hi,
thanks for reporting. The issue is quite simply a mismatch between the version installed (0.7)
and the documentation (latest/master). The API has been polished quite a bit since 0.7
```py
decor = arbor.decor()
decor.set_property(Vm=-40)
decor.paint('"soma"', arbor.density("hh"))
decor.place('"midpoint"', arbor.iclamp(10, 2, 0.8), "iclamp")
decor.place('"midpoint"', arbor.spike_detector(-10), "detector")
```
is working on 0.7; we introduced the chaining approach shortly after among others.

Here's a link to the correct docs
https://docs.arbor-sim.org/en/v0.7/tutorial/single_cell_model.html

**Comment by mgiugliano** [comment]
Thank you for correcting the documentation, reflecting the new and polished API.
