### ISSUE TITLE
Compilation failing with Intel compiler

### ISSUE THREAD

**Issue by vkarak** [arbor-sim/arbor#583]
I am getting the following error when trying to compile with ICC 17.0.4.

```
arbor/mechcat.cpp(138): error: call of an objec
t of a class type without appropriate operator() or conversion functions to pointer-to-function type
              self(self, p->parent, mptr);
              ^
          detected during instantiation of function "lambda [](auto &, const std::__cxx11::string &, arb::mechanism *)->void [
with <auto-1>=lambda [](auto &, const std::__cxx11::string &, arb::mechanism *)->void]" at line 145
```

Also, I am getting a bunch of warning about attributes passing optimisation options, such as the following one:

```
arbor/util/compat.hpp(50): warning #317
5: unrecognized gcc optimization level
  __attribute((optimize("no-tree-vectorize")))
```

Here is how I configure and compile on Daint:

```
module load daint-gpu
module unload PrgEnv-cray
module load PrgEnv-intel
module load CMake
module load gcc/7.1.0
export CRAYPE_LINK_TYPE=dynamic
mkdir build
cd build
cmake .. -DARB_WITH_ASSERTIONS=ON
make -j
```

**Comment by bcumming** [comment]
The vectorized back ends have been optimized quite aggressively so that you should get better performance using gcc and explicit vectorization.

To generate code for the daint-gpu nodes with gcc try:

```
cmake .. -DARB_VECTORIZE=ON -DARB_ARCH=haswell
```

**Comment by halfflat** [comment]
I think we have basically three options:
1. Not support icpc until Intel fixes their compiler.
2. Make `apply_globals` a top-level (recursive) function.
3. Substitute recursive lambda with less efficient `std::function`-style recursion, transforming e.g.
    ```
        auto fac = [](auto&& self, int n, int acc) -> int {
            return n<2? acc: self(self, n-1, acc*n);
        };
        fac(fac, 10, 1);
    ```
    with
    ```
        stl::function<int (int, int)> fac = [&fac](int n, int acc) -> int {
            return n<2? acc: self(self, n-1, acc*n);
        };
        fac(10, 1);
    ```

Any preferences?

**Comment by bcumming** [comment]
1. if we drop it, we drop it for good, because there will always be more bugs with the Intel compiler.

I would go for 2., because it is simpler to understand.

**Comment by bcumming** [comment]
Support for Intel has been dropped.
